# %%
# -*- coding: utf-8 -*-
"""自己紹介ユーザーのコメント数集計.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NgV87lKvqceBjfP9eFuAE_b9hrPO504N
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import re
from matplotlib import rcParams
sns.set(font="IPAexGothic", style="whitegrid")

# 自己紹介してからの日時
count = pd.read_csv("input/selfintro_except_murakami.csv")

count

# %%
# 自己紹介ありのユーザーだけに絞る
count_only_intro = count[count["自己紹介"] == "あり"]

# 一日あたりのコメント数の欄を作る
count_only_intro["1日あたりのコメント数"] = count_only_intro["comments"] / \
    count_only_intro["自己紹介してからの日数"]

# 一日あたりのコメント数を基準に構成比を出す
count_only_intro["1日あたりのコメント数構成比[%]"] = (
    count_only_intro["1日あたりのコメント数"]/sum(count_only_intro["1日あたりのコメント数"]))*100

count_only_intro

# "1日あたりのコメント数構成比[%]"でソートする
count_only_intro = count_only_intro.sort_values(
    by="1日あたりのコメント数構成比[%]", ascending=False)

# "1日あたりのコメント数構成比[%]の累積相対度数を出す
count_only_intro["累積相対度数[%]"] = count_only_intro["1日あたりのコメント数構成比[%]"].cumsum()

# indexを振り直す
count_only_intro = count_only_intro.reset_index()

count_only_intro['user_name'] = [f'ユーザー{i}さん' for i in range(
    len(count_only_intro['talk_user']))]

# count_only_intさん
count_only_intro['user_name']

# 村上さん除いたパレート図（自己紹介ありのみ）
ax1 = sns.barplot(
    x=count_only_intro["user_name"], y="1日あたりのコメント数", data=count_only_intro)
ax2 = ax1.twinx()

count_only_intro["累積相対度数[%]"].plot(
    figsize=(30, 3), color='orange', ax=ax2, marker='o')
xlabels = ax1.get_xticklabels()
ax1.set_xticklabels(xlabels, rotation='vertical', fontsize=20)
ax1.set_ylabel("コメント数/日", fontsize=20)
ax2.set_ylabel("構成比（％）", fontsize=18)
ax2.set_ylim([0, 100])
ax1.tick_params(axis="y", labelsize=15, color="white")
ax2.tick_params(axis="y", labelsize=15, color="white")

# ax1の目盛り線を消した
ax1.grid(which="major", axis="y", color="blue", alpha=0.8,
         linestyle="", linewidth=1)

ax2.set_yticks(list(range(0, 110, 10)))

count_only_intro.to_csv("1日あたりのコメント数.csv")


# %%
